/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityCheckRouteImport } from './routes/security-check'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LinkAccountRouteImport } from './routes/link-account'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddMoneyRouteImport } from './routes/add-money'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SendIndexRouteImport } from './routes/send.index'
import { Route as SecurityCheckIndexRouteImport } from './routes/security-check.index'
import { Route as RequestIndexRouteImport } from './routes/request.index'
import { Route as CryptoIndexRouteImport } from './routes/crypto.index'
import { Route as AddMoneyIndexRouteImport } from './routes/add-money.index'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as TransferSavingsRouteImport } from './routes/transfer.savings'
import { Route as TransferBankRouteImport } from './routes/transfer.bank'
import { Route as SendSuccessRouteImport } from './routes/send.success'
import { Route as SendAmountRouteImport } from './routes/send.amount'
import { Route as SecurityCheckConfirmedRouteImport } from './routes/security-check.confirmed'
import { Route as SecurityCheckCodeRouteImport } from './routes/security-check.code'
import { Route as RequestSuccessRouteImport } from './routes/request.success'
import { Route as RequestAmountRouteImport } from './routes/request.amount'
import { Route as CryptoSuccessRouteImport } from './routes/crypto.success'
import { Route as CryptoSymbolRouteImport } from './routes/crypto.$symbol'
import { Route as AddMoneySuccessRouteImport } from './routes/add-money.success'
import { Route as AddMoneyReviewRouteImport } from './routes/add-money.review'
import { Route as AddMoneyMethodRouteImport } from './routes/add-money.method'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'
import { Route as CryptoSellSymbolRouteImport } from './routes/crypto.sell.$symbol'
import { Route as CryptoBuySymbolRouteImport } from './routes/crypto.buy.$symbol'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckRoute = SecurityCheckRouteImport.update({
  id: '/security-check',
  path: '/security-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkAccountRoute = LinkAccountRouteImport.update({
  id: '/link-account',
  path: '/link-account',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyRoute = AddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SendIndexRoute = SendIndexRouteImport.update({
  id: '/send/',
  path: '/send/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckIndexRoute = SecurityCheckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityCheckRoute,
} as any)
const RequestIndexRoute = RequestIndexRouteImport.update({
  id: '/request/',
  path: '/request/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoIndexRoute = CryptoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CryptoRoute,
} as any)
const AddMoneyIndexRoute = AddMoneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddMoneyRoute,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActivityRoute,
} as any)
const TransferSavingsRoute = TransferSavingsRouteImport.update({
  id: '/transfer/savings',
  path: '/transfer/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferBankRoute = TransferBankRouteImport.update({
  id: '/transfer/bank',
  path: '/transfer/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const SendSuccessRoute = SendSuccessRouteImport.update({
  id: '/send/success',
  path: '/send/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SendAmountRoute = SendAmountRouteImport.update({
  id: '/send/amount',
  path: '/send/amount',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckConfirmedRoute = SecurityCheckConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => SecurityCheckRoute,
} as any)
const SecurityCheckCodeRoute = SecurityCheckCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => SecurityCheckRoute,
} as any)
const RequestSuccessRoute = RequestSuccessRouteImport.update({
  id: '/request/success',
  path: '/request/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAmountRoute = RequestAmountRouteImport.update({
  id: '/request/amount',
  path: '/request/amount',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoSuccessRoute = CryptoSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoSymbolRoute = CryptoSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => CryptoRoute,
} as any)
const AddMoneySuccessRoute = AddMoneySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AddMoneyRoute,
} as any)
const AddMoneyReviewRoute = AddMoneyReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AddMoneyRoute,
} as any)
const AddMoneyMethodRoute = AddMoneyMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AddMoneyRoute,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActivityRoute,
} as any)
const CryptoSellSymbolRoute = CryptoSellSymbolRouteImport.update({
  id: '/sell/$symbol',
  path: '/sell/$symbol',
  getParentRoute: () => CryptoRoute,
} as any)
const CryptoBuySymbolRoute = CryptoBuySymbolRouteImport.update({
  id: '/buy/$symbol',
  path: '/buy/$symbol',
  getParentRoute: () => CryptoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/add-money': typeof AddMoneyRouteWithChildren
  '/auth': typeof AuthRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/deals': typeof DealsRoute
  '/finances': typeof FinancesRoute
  '/link-account': typeof LinkAccountRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/security-check': typeof SecurityCheckRouteWithChildren
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/wallet': typeof WalletRoute
  '/activity/$id': typeof ActivityIdRoute
  '/add-money/method': typeof AddMoneyMethodRoute
  '/add-money/review': typeof AddMoneyReviewRoute
  '/add-money/success': typeof AddMoneySuccessRoute
  '/crypto/$symbol': typeof CryptoSymbolRoute
  '/crypto/success': typeof CryptoSuccessRoute
  '/request/amount': typeof RequestAmountRoute
  '/request/success': typeof RequestSuccessRoute
  '/security-check/code': typeof SecurityCheckCodeRoute
  '/security-check/confirmed': typeof SecurityCheckConfirmedRoute
  '/send/amount': typeof SendAmountRoute
  '/send/success': typeof SendSuccessRoute
  '/transfer/bank': typeof TransferBankRoute
  '/transfer/savings': typeof TransferSavingsRoute
  '/activity/': typeof ActivityIndexRoute
  '/add-money/': typeof AddMoneyIndexRoute
  '/crypto/': typeof CryptoIndexRoute
  '/request/': typeof RequestIndexRoute
  '/security-check/': typeof SecurityCheckIndexRoute
  '/send/': typeof SendIndexRoute
  '/crypto/buy/$symbol': typeof CryptoBuySymbolRoute
  '/crypto/sell/$symbol': typeof CryptoSellSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/finances': typeof FinancesRoute
  '/link-account': typeof LinkAccountRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/wallet': typeof WalletRoute
  '/activity/$id': typeof ActivityIdRoute
  '/add-money/method': typeof AddMoneyMethodRoute
  '/add-money/review': typeof AddMoneyReviewRoute
  '/add-money/success': typeof AddMoneySuccessRoute
  '/crypto/$symbol': typeof CryptoSymbolRoute
  '/crypto/success': typeof CryptoSuccessRoute
  '/request/amount': typeof RequestAmountRoute
  '/request/success': typeof RequestSuccessRoute
  '/security-check/code': typeof SecurityCheckCodeRoute
  '/security-check/confirmed': typeof SecurityCheckConfirmedRoute
  '/send/amount': typeof SendAmountRoute
  '/send/success': typeof SendSuccessRoute
  '/transfer/bank': typeof TransferBankRoute
  '/transfer/savings': typeof TransferSavingsRoute
  '/activity': typeof ActivityIndexRoute
  '/add-money': typeof AddMoneyIndexRoute
  '/crypto': typeof CryptoIndexRoute
  '/request': typeof RequestIndexRoute
  '/security-check': typeof SecurityCheckIndexRoute
  '/send': typeof SendIndexRoute
  '/crypto/buy/$symbol': typeof CryptoBuySymbolRoute
  '/crypto/sell/$symbol': typeof CryptoSellSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/add-money': typeof AddMoneyRouteWithChildren
  '/auth': typeof AuthRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/deals': typeof DealsRoute
  '/finances': typeof FinancesRoute
  '/link-account': typeof LinkAccountRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/security-check': typeof SecurityCheckRouteWithChildren
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/wallet': typeof WalletRoute
  '/activity/$id': typeof ActivityIdRoute
  '/add-money/method': typeof AddMoneyMethodRoute
  '/add-money/review': typeof AddMoneyReviewRoute
  '/add-money/success': typeof AddMoneySuccessRoute
  '/crypto/$symbol': typeof CryptoSymbolRoute
  '/crypto/success': typeof CryptoSuccessRoute
  '/request/amount': typeof RequestAmountRoute
  '/request/success': typeof RequestSuccessRoute
  '/security-check/code': typeof SecurityCheckCodeRoute
  '/security-check/confirmed': typeof SecurityCheckConfirmedRoute
  '/send/amount': typeof SendAmountRoute
  '/send/success': typeof SendSuccessRoute
  '/transfer/bank': typeof TransferBankRoute
  '/transfer/savings': typeof TransferSavingsRoute
  '/activity/': typeof ActivityIndexRoute
  '/add-money/': typeof AddMoneyIndexRoute
  '/crypto/': typeof CryptoIndexRoute
  '/request/': typeof RequestIndexRoute
  '/security-check/': typeof SecurityCheckIndexRoute
  '/send/': typeof SendIndexRoute
  '/crypto/buy/$symbol': typeof CryptoBuySymbolRoute
  '/crypto/sell/$symbol': typeof CryptoSellSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/add-money'
    | '/auth'
    | '/crypto'
    | '/deals'
    | '/finances'
    | '/link-account'
    | '/payments'
    | '/profile'
    | '/security-check'
    | '/settings'
    | '/splash'
    | '/wallet'
    | '/activity/$id'
    | '/add-money/method'
    | '/add-money/review'
    | '/add-money/success'
    | '/crypto/$symbol'
    | '/crypto/success'
    | '/request/amount'
    | '/request/success'
    | '/security-check/code'
    | '/security-check/confirmed'
    | '/send/amount'
    | '/send/success'
    | '/transfer/bank'
    | '/transfer/savings'
    | '/activity/'
    | '/add-money/'
    | '/crypto/'
    | '/request/'
    | '/security-check/'
    | '/send/'
    | '/crypto/buy/$symbol'
    | '/crypto/sell/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deals'
    | '/finances'
    | '/link-account'
    | '/payments'
    | '/profile'
    | '/settings'
    | '/splash'
    | '/wallet'
    | '/activity/$id'
    | '/add-money/method'
    | '/add-money/review'
    | '/add-money/success'
    | '/crypto/$symbol'
    | '/crypto/success'
    | '/request/amount'
    | '/request/success'
    | '/security-check/code'
    | '/security-check/confirmed'
    | '/send/amount'
    | '/send/success'
    | '/transfer/bank'
    | '/transfer/savings'
    | '/activity'
    | '/add-money'
    | '/crypto'
    | '/request'
    | '/security-check'
    | '/send'
    | '/crypto/buy/$symbol'
    | '/crypto/sell/$symbol'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/add-money'
    | '/auth'
    | '/crypto'
    | '/deals'
    | '/finances'
    | '/link-account'
    | '/payments'
    | '/profile'
    | '/security-check'
    | '/settings'
    | '/splash'
    | '/wallet'
    | '/activity/$id'
    | '/add-money/method'
    | '/add-money/review'
    | '/add-money/success'
    | '/crypto/$symbol'
    | '/crypto/success'
    | '/request/amount'
    | '/request/success'
    | '/security-check/code'
    | '/security-check/confirmed'
    | '/send/amount'
    | '/send/success'
    | '/transfer/bank'
    | '/transfer/savings'
    | '/activity/'
    | '/add-money/'
    | '/crypto/'
    | '/request/'
    | '/security-check/'
    | '/send/'
    | '/crypto/buy/$symbol'
    | '/crypto/sell/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRouteWithChildren
  AddMoneyRoute: typeof AddMoneyRouteWithChildren
  AuthRoute: typeof AuthRoute
  CryptoRoute: typeof CryptoRouteWithChildren
  DealsRoute: typeof DealsRoute
  FinancesRoute: typeof FinancesRoute
  LinkAccountRoute: typeof LinkAccountRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SecurityCheckRoute: typeof SecurityCheckRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
  WalletRoute: typeof WalletRoute
  RequestAmountRoute: typeof RequestAmountRoute
  RequestSuccessRoute: typeof RequestSuccessRoute
  SendAmountRoute: typeof SendAmountRoute
  SendSuccessRoute: typeof SendSuccessRoute
  TransferBankRoute: typeof TransferBankRoute
  TransferSavingsRoute: typeof TransferSavingsRoute
  RequestIndexRoute: typeof RequestIndexRoute
  SendIndexRoute: typeof SendIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-check': {
      id: '/security-check'
      path: '/security-check'
      fullPath: '/security-check'
      preLoaderRoute: typeof SecurityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-account': {
      id: '/link-account'
      path: '/link-account'
      fullPath: '/link-account'
      preLoaderRoute: typeof LinkAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money': {
      id: '/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/': {
      id: '/send/'
      path: '/send'
      fullPath: '/send/'
      preLoaderRoute: typeof SendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-check/': {
      id: '/security-check/'
      path: '/'
      fullPath: '/security-check/'
      preLoaderRoute: typeof SecurityCheckIndexRouteImport
      parentRoute: typeof SecurityCheckRoute
    }
    '/request/': {
      id: '/request/'
      path: '/request'
      fullPath: '/request/'
      preLoaderRoute: typeof RequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/'
      fullPath: '/crypto/'
      preLoaderRoute: typeof CryptoIndexRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/add-money/': {
      id: '/add-money/'
      path: '/'
      fullPath: '/add-money/'
      preLoaderRoute: typeof AddMoneyIndexRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/activity/': {
      id: '/activity/'
      path: '/'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof ActivityRoute
    }
    '/transfer/savings': {
      id: '/transfer/savings'
      path: '/transfer/savings'
      fullPath: '/transfer/savings'
      preLoaderRoute: typeof TransferSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer/bank': {
      id: '/transfer/bank'
      path: '/transfer/bank'
      fullPath: '/transfer/bank'
      preLoaderRoute: typeof TransferBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/success': {
      id: '/send/success'
      path: '/send/success'
      fullPath: '/send/success'
      preLoaderRoute: typeof SendSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/amount': {
      id: '/send/amount'
      path: '/send/amount'
      fullPath: '/send/amount'
      preLoaderRoute: typeof SendAmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-check/confirmed': {
      id: '/security-check/confirmed'
      path: '/confirmed'
      fullPath: '/security-check/confirmed'
      preLoaderRoute: typeof SecurityCheckConfirmedRouteImport
      parentRoute: typeof SecurityCheckRoute
    }
    '/security-check/code': {
      id: '/security-check/code'
      path: '/code'
      fullPath: '/security-check/code'
      preLoaderRoute: typeof SecurityCheckCodeRouteImport
      parentRoute: typeof SecurityCheckRoute
    }
    '/request/success': {
      id: '/request/success'
      path: '/request/success'
      fullPath: '/request/success'
      preLoaderRoute: typeof RequestSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/amount': {
      id: '/request/amount'
      path: '/request/amount'
      fullPath: '/request/amount'
      preLoaderRoute: typeof RequestAmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/success': {
      id: '/crypto/success'
      path: '/success'
      fullPath: '/crypto/success'
      preLoaderRoute: typeof CryptoSuccessRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/$symbol': {
      id: '/crypto/$symbol'
      path: '/$symbol'
      fullPath: '/crypto/$symbol'
      preLoaderRoute: typeof CryptoSymbolRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/add-money/success': {
      id: '/add-money/success'
      path: '/success'
      fullPath: '/add-money/success'
      preLoaderRoute: typeof AddMoneySuccessRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/add-money/review': {
      id: '/add-money/review'
      path: '/review'
      fullPath: '/add-money/review'
      preLoaderRoute: typeof AddMoneyReviewRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/add-money/method': {
      id: '/add-money/method'
      path: '/method'
      fullPath: '/add-money/method'
      preLoaderRoute: typeof AddMoneyMethodRouteImport
      parentRoute: typeof AddMoneyRoute
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof ActivityRoute
    }
    '/crypto/sell/$symbol': {
      id: '/crypto/sell/$symbol'
      path: '/sell/$symbol'
      fullPath: '/crypto/sell/$symbol'
      preLoaderRoute: typeof CryptoSellSymbolRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/crypto/buy/$symbol': {
      id: '/crypto/buy/$symbol'
      path: '/buy/$symbol'
      fullPath: '/crypto/buy/$symbol'
      preLoaderRoute: typeof CryptoBuySymbolRouteImport
      parentRoute: typeof CryptoRoute
    }
  }
}

interface ActivityRouteChildren {
  ActivityIdRoute: typeof ActivityIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
}

const ActivityRouteChildren: ActivityRouteChildren = {
  ActivityIdRoute: ActivityIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
}

const ActivityRouteWithChildren = ActivityRoute._addFileChildren(
  ActivityRouteChildren,
)

interface AddMoneyRouteChildren {
  AddMoneyMethodRoute: typeof AddMoneyMethodRoute
  AddMoneyReviewRoute: typeof AddMoneyReviewRoute
  AddMoneySuccessRoute: typeof AddMoneySuccessRoute
  AddMoneyIndexRoute: typeof AddMoneyIndexRoute
}

const AddMoneyRouteChildren: AddMoneyRouteChildren = {
  AddMoneyMethodRoute: AddMoneyMethodRoute,
  AddMoneyReviewRoute: AddMoneyReviewRoute,
  AddMoneySuccessRoute: AddMoneySuccessRoute,
  AddMoneyIndexRoute: AddMoneyIndexRoute,
}

const AddMoneyRouteWithChildren = AddMoneyRoute._addFileChildren(
  AddMoneyRouteChildren,
)

interface CryptoRouteChildren {
  CryptoSymbolRoute: typeof CryptoSymbolRoute
  CryptoSuccessRoute: typeof CryptoSuccessRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
  CryptoBuySymbolRoute: typeof CryptoBuySymbolRoute
  CryptoSellSymbolRoute: typeof CryptoSellSymbolRoute
}

const CryptoRouteChildren: CryptoRouteChildren = {
  CryptoSymbolRoute: CryptoSymbolRoute,
  CryptoSuccessRoute: CryptoSuccessRoute,
  CryptoIndexRoute: CryptoIndexRoute,
  CryptoBuySymbolRoute: CryptoBuySymbolRoute,
  CryptoSellSymbolRoute: CryptoSellSymbolRoute,
}

const CryptoRouteWithChildren =
  CryptoRoute._addFileChildren(CryptoRouteChildren)

interface SecurityCheckRouteChildren {
  SecurityCheckCodeRoute: typeof SecurityCheckCodeRoute
  SecurityCheckConfirmedRoute: typeof SecurityCheckConfirmedRoute
  SecurityCheckIndexRoute: typeof SecurityCheckIndexRoute
}

const SecurityCheckRouteChildren: SecurityCheckRouteChildren = {
  SecurityCheckCodeRoute: SecurityCheckCodeRoute,
  SecurityCheckConfirmedRoute: SecurityCheckConfirmedRoute,
  SecurityCheckIndexRoute: SecurityCheckIndexRoute,
}

const SecurityCheckRouteWithChildren = SecurityCheckRoute._addFileChildren(
  SecurityCheckRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRouteWithChildren,
  AddMoneyRoute: AddMoneyRouteWithChildren,
  AuthRoute: AuthRoute,
  CryptoRoute: CryptoRouteWithChildren,
  DealsRoute: DealsRoute,
  FinancesRoute: FinancesRoute,
  LinkAccountRoute: LinkAccountRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SecurityCheckRoute: SecurityCheckRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
  WalletRoute: WalletRoute,
  RequestAmountRoute: RequestAmountRoute,
  RequestSuccessRoute: RequestSuccessRoute,
  SendAmountRoute: SendAmountRoute,
  SendSuccessRoute: SendSuccessRoute,
  TransferBankRoute: TransferBankRoute,
  TransferSavingsRoute: TransferSavingsRoute,
  RequestIndexRoute: RequestIndexRoute,
  SendIndexRoute: SendIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
